### ISSUE TITLE
[DISCUSSION] 모듈 선택 시 고려 사항

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#27]
#### Major module: Use a Framework as backend.
필수
#### Minor module: Use a front-end framework or toolkit.
필수
#### Minor module: Use a database for the backend.
필수
#### Major module: Store the score of a tournament in the Blockchain.
Blockchain 관련 지식도 없고 Solidity는 아예 처음 들어 봄
일단 PostgreSQL로 관리하다가 필요하면 도입

#### Major module: Standard user management, authentication, users across tournaments.
필수
#### Major module: Implementing a remote authentication.
42 과제니까 42 인증은 꼭 적용했으면 함

#### Major module: Remote players
로컬 플레이만으로는 부족
#### Major module: Multiplayers (more than 2 in the same game).
예쁜 UI가 안 나올 듯 함
#### Major module: Add Another Game with User History and Matchmaking.
괜찮은데 사이트의 정체성이 흔들릴 듯
#### Minor module: Game Customization Options.
paddle 크기, 속도, 점수 등
#### Major module: Live chat.
가성비 별로인 듯 해서 일단 보류

#### Major module: Introduce an AI Opponent.
가성비 쓰레기, 전담하는 팀원이 없다면 버려야 함
#### Minor module: User and Game Stats Dashboards
살짝 귀찮지만 괜찮아 보임, 시각화는 라이브리러 활용

#### Major module: Implement WAF/ModSecurity with Hardened Configuration and HashiCorp Vault for Secrets Management.
원하는 팀원이 없다면 바로 버림
#### Minor module: GDPR Compliance Options with User Anonymization, Local Data Management, and Account Deletion.
원하는 팀원이 없다면 버릴 예정이지만 고려해볼만 함
#### Major module: Implement Two-Factor Authentication (2FA) and JWT.
2단계 인증은 멋지다, 하지만 우선순위는 낮추는 것으로

#### Major module: Infrastructure Setup for Log Management.
팀장님이 하고 싶다고 함
#### Minor module: Monitoring system.
팀장님이 하고 싶다고 함
#### Major module: Designing the Backend as Microservices.
팀장님이 하고 싶다고 함

#### Major module: Use of advanced 3D techniques.
다른 모듈과 상당히 독립적, 하지만 그래픽에 관심 있는 팀원이 없다면 버리는 것으로

#### Minor module: Support on all devices.
마우스 이벤트 처리, css 미디어 쿼리, 우선순위는 낮추고 싶음
#### Minor module: Expanding Browser Compatibility.
테스트만 잘 하면 날로 먹을 수 있음
#### Minor module: Multiple language supports.
가능하기는 한데 그렇게 하고 싶지는 않음
#### Minor module: Add accessibility for Visually Impaired Users.
시각 장애인이 퐁 게임을 어떻게 하는가
#### Minor module: Server-Side Rendering (SSR) Integration.
방향도 모르겠고 비용이 커 보임

#### Major module: Replacing Basic Pong with Server-Side Pong and Implementing an API.
다른 모듈 하려면 필요해 보이고 어려워 보이지도 않음
#### Major module: Enabling Pong Gameplay via CLI against Web Users with API Integration.
가성비 쓰레기, 전담하는 팀원이 없다면 버려야 함

**Comment by cryscham123** [comment]
## 무조건 할거
### WEB

- Major module: Use a Framework as backend.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  In this major module, you are required to utilize a specific web framework for your
  backend development, and that framework is Django.
  </blockquote>
  </p>
  </details>
  필수

- Minor module: Use a front-end framework or toolkit.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  Your frontend development will utilize the Bootstrap toolkit.
  </blockquote>
  </p>
  </details>
  필수

- Minor module: Use a database for the backend.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  The designated database for all DB instances in your project is PostgreSQL.<br>
  This choice guarantees data consistency and compatibility across all project components and may be a prerequisite for 
  other modules, such as the backend Framework module.
  </blockquote>
  </p>
  </details> 
  필수

### USER MANAGEMENT

- Major module: Standard user management, authentication, users across tournaments.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  <ul>
  <li>Users can subscribe to the website in a secure way.</li>
  <li>Registered users can log in in a secure way.</li>
  <li>Users can select a unique display name to play the tournaments.</li>
  <li>Users can update their information.</li>
  <li>Users can upload an avatar, with a default option if none is provided.</li>
  <li>Users can add others as friends and view their online status.</li>
  <li>User profiles display stats, such as wins and losses.</li>
  <li>Each user has a Match History including 1v1 games, dates, and relevant details, accessible to logged-in users.</li>
  </ul>  
  </blockquote>
  </p>
  </details>
  필수

- Major module: Implementing a remote authentication.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  In this major module, the goal is to implement the following authentication system:<br>
  OAuth 2.0 authentication with 42.<br>
  Key features and objectives include:<br>
  <ul>
  <li>Integrate the authentication system, allowing users to securely sign in.</li>
  <li>Obtain the necessary credentials and permissions from the authority to enable
  a secure login.</li>
  <li>implement user-friendly login and authorization flows that adhere to best practices and security standards.</li>
  <li>Ensure the secure exchange of authentication tokens and user information
  between the web application and the authentication provider.</li>
  </ul>
  This major module aims to get a remote user authentication, providing users with
  a secure and convenient way to access the web application.
  </blockquote>
  </p>
  </details> 
  42 과제니까 42 인증은 꼭 적용했으면 함

### GAMEPLAY AND USER EXPERIENCE

- Major module: Remote players
  <details><summary>detail</summary>
  <p>
  <blockquote>
  It is possible to have two distant players. Each player is located on a separated
  computer, accessing the same website and playing the same Pong game.
  </blockquote>
  </p>
  </details>
  로컬 플레이만으로는 부족

- Minor module: Game Customization Options.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  In this minor module, the goal is to provide customization options for all available
  games on the platform.<br>
  Key features and objectives include:<br>
  <ul>
  <li>Offer customization features, such as power-ups, attacks, or different maps,
  that enhance the gameplay experience.</li>
  <li>Allow users to choose a default version of the game with basic features if they
  prefer a simpler experience.</li>
  <li>Ensure that customization options are available and applicable to all games
  offered on the platform.</li>
  <li>Implement user-friendly settings menus or interfaces for adjusting game parameters.</li>
  <li>Maintain consistency in customization features across all games to provide a
  unified user experience.</li>
  </ul>
  This module aims to give users the flexibility to tailor their gaming experience
  across all available games by providing a variety of customization options while
  also offering a default version for those who prefer a straightforward gameplay
  experience.
  </blockquote>
  </p>
  </details> 
  paddle 크기, 속도, 점수 등

### CYBERSECURITY

- Major module: Implement Two-Factor Authentication (2FA) and JWT.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  In this major module, the goal is to enhance security and user authentication
  by introducing Two-Factor Authentication (2FA) and utilizing JSON Web Tokens
  (JWT).<br>
  Key features and objectives include:<br>
  <ul>
  <li>Implement Two-Factor Authentication (2FA) as an additional layer of security
  for user accounts, requiring users to provide a secondary verification method,
  such as a one-time code, in addition to their password.</li>
  <li>Utilize JSON Web Tokens (JWT) as a secure method for authentication and
  authorization, ensuring that user sessions and access to resources are managed
  securely.</li>
  <li>Provide a user-friendly setup process for enabling 2FA, with options for SMS
  codes, authenticator apps, or email-based verification.</li>
  <li>Ensure that JWT tokens are issued and validated securely to prevent unauthorized access to user accounts and 
  sensitive data.</li>
  </ul>
  This major module aims to strengthen user account security by offering Two-Factor
  Authentication (2FA) and enhancing authentication and authorization through the
  use of JSON Web Tokens (JWT).
  </blockquote>
  </p>
  </details> 
  2단계 인증은 멋지다

### DEVOPS

- Major module: Infrastructure Setup for Log Management.

  <details><summary>detail</summary>
  <p>
  <blockquote>
  In this major module, the objective is to establish a robust infrastructure for log
  management and analysis using the ELK stack (Elasticsearch, Logstash, Kibana).<br>
  Key features and goals include:<br>
  <li>Deploy Elasticsearch to efficiently store and index log data, making it easily
  searchable and accessible.</li>
  <li>Configure Logstash to collect, process, and transform log data from various
  sources and send it to Elasticsearch.</li>
  <li>Set up Kibana for visualizing log data, creating dashboards, and generating
  insights from log events.</li>
  <li>Define data retention and archiving policies to manage the storage of log data
  effectively.</li>
  <li>Implement security measures to protect log data and access to the ELK stack
  components.</li>
  This major module aims to establish a powerful log management and analysis system using the ELK stack, enabling 
  effective troubles
  </blockquote>
  </p>
  </details> 

- Major module: Designing the Backend as Microservices.
  <details><summary>detail</summary>
  <p>
  In this major module, the goal is to architect the backend of the system using a
  microservices approach.<br>
  Key features and objectives include:<br>
  <li>Divide the backend into smaller, loosely-coupled microservices, each responsible for specific functions or features. 
  </li>
  <li>Define clear boundaries and interfaces between microservices to enable independent development, deployment, and 
  scaling.</li>
  <li>Implement communication mechanisms between microservices, such as RESTful APIs or message queues, to 
  facilitate data exchange and coordination.</li>
  <li>Ensure that each microservice is responsible for a single, well-defined task or
  business capability, promoting maintainability and scalability.</li>
  This major module aims to enhance the system’s architecture by adopting a microservices design approach, enabling 
  greater flexibility, scalability, and maintainability of the backend components.
  </p>
  </details> 

### ACCSSIBILITY

- Minor module: Support on all devices.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  In this module, the main focus is to ensure that your website works seamlessly on
  all types of devices.<br>
  Key features and objectives include:<br>
  <ul>
  <li>Make sure the website is responsive, adapting to different screen sizes and orientations, ensuring a consistent user 
  experience on desktops, laptops, tablets,
  and smartphones.</li>
  <li>Ensure that users can easily navigate and interact with the website using
  different input methods, such as touchscreens, keyboards, and mice, depending
  on the device they are using.</li>
  </ul>
  This module aims to provide a consistent and user-friendly experience on all devices,
  maximizing accessibility and user satisfaction
  </blockquote> 
  </p>
  </details> 
  마우스 이벤트 처리, css 미디어 쿼리

- Minor module: Expanding Browser Compatibility.
  <details><summary>detail</summary>
  <p>
  <blockquote>
  In this minor module, the objective is to enhance the compatibility of the web
  application by adding support for an additional web browser.<br>
  Key features and objectives include:<br>
  <ul>
  <li>Extend browser support to include an additional web browser, ensuring that
  users can access and use the application seamlessly.</li>
  <li>Conduct thorough testing and optimization to ensure that the web application
  functions correctly and displays correctly in the newly supported browser.</li>
  <li>Address any compatibility issues or rendering discrepancies that may arise in
  the added web browser.</li>
  <li>Ensure a consistent user experience across all supported browsers, maintaining
  usability and functionality.</li>
  </ul>
  This minor module aims to broaden the accessibility of the web application by
  supporting an additional web browser, providing users with more choices for their
  browsing experience.
  </blockquote>
  </p>
  </details> 
  테스트만 잘 하면 날로 먹을 수 있음

...이미 무조건 할 것만으로 125점 조건인 minor module 19개가 채워짐.

**Comment by cryscham123** [comment]
## 선택적으로 할 것
### WEB

- Major module: Store the score of a tournament in the Blockchain.
  
  <details><summary>details</summary>
  <p>
  <blockquote>
  This Major module focuses on implementing a feature within the Pong website to
  store tournament scores securely on a blockchain.<br>
   It is essential to clarify that for
  development and testing purposes, we will utilize a testing blockchain environment.<br>
  The chosen blockchain for this implementation is Ethereum , and Solidity will be
  the programming language used for smart contract development.<br>
  <ul>
  <li>Blockchain Integration: The primary goal of this module is to seamlessly integrate blockchain technology, specifically Ethereum , into the Pong website.<br>
  This integration ensures the secure and immutable storage of tournament
  scores, providing players with a transparent and tamper-proof record of their
  gaming achievements.</li>
  <li>Solidity Smart Contracts: To interact with the blockchain, we will develop
  Solidity smart contracts.<br>These contracts will be responsible for recording,
  managing, and retrieving tournament scores.</li>
  <li>Testing Blockchain: As mentioned earlier, a testing blockchain will be employed for development and testing purposes.<br>This ensures that all blockchainrelated functionalities are thoroughly validated without any risks associated
  with a live blockchain.</li>
  <li>Interoperability: This module may have dependencies on other modules, particularly the Backend Framework module.<br>Integrating blockchain functionality might necessitate adjustments in the backend to accommodate interactions
  with the blockchain.</li>
  </ul>
  By implementing this module, we aim to enhance the Pong website by introducing
  a blockchain-based score storage system.<br>
  Users will benefit from the added layer
  of security and transparency, ensuring the integrity of their gaming scores.<br>
  The module emphasizes the use of a testing blockchain environment to minimize risks
  associated with blockchain development.
  </blockquote>
  </p>
  </details> 
  일단 PostgreSQL로 관리하다가 필요하면 도입.

### Gameplay and user experience

- Major module: Multiplayers (more than 2 in the same game).
  
  <details><summary>details</summary>
  <p>
  <blockquote>
  It is possible to have more than two players.<br>
  Each player needs a live control (so the previous “Distant players” module is highly recommanded).<br>
  It’s up to you to define how the game could be played with 3, 4, 5, 6 ... players.<br>
  Along with the regular 2 players game, you can choose a single number of players, greater than
  2, for this multiplayer module.<br>
  Ex: 4 players can play on a squarred board, each
  player owns one unique side of the square.
  </bockquote>
  </p>
  </details> 
  예쁜 UI가 안 나올 듯 함

- Major module: Add Another Game with User History and Matchmaking.

  <details><summary>details</summary>
  <p>
  <blockquote>
  In this major module, the objective is to introduce a new game, distinct from Pong,
  and incorporate features such as user history tracking and matchmaking.<br>
  Key features and goals include:<br>
  <ul>
  <li>Develop a new, engaging game to diversify the platform’s offerings and entertain users.</li>
  <li>Implement user history tracking to record and display individual user’s gameplay statistics.</li>
  <li>Create a matchmaking system to allow users to find opponents and participate
  in fair and balanced matches.</li>
  <li>Ensure that user game history and matchmaking data are stored securely and
  remain up-to-date.</li>
  <li>Optimize the performance and responsiveness of the new game to provide an
  enjoyable user experience.<br> Regularly update and maintain the game to fix
  bugs, add new features, and enhance gameplay.</li>
  </ul>
  This major module aims to expand your platform by introducing a new game,
  enhancing user engagement with gameplay history, and facilitating matchmaking
  for an enjoyable gaming experience
  </blockquote>
  </p>
  </details> 
  괜찮은데 사이트의 정체성이 흔들릴 듯.

- Major module: Live chat.

  <details><summary>details</summary>
  <p>
  <blockquote>
  You have to create a chat for your users in this module:
  <ul>
  <li>The user should be able to send direct messages to other users.</li>
  <li>The user should be able to block other users.<br>This way, they will see no more
  messages from the account they blocked.</li>
  <li>The user should be able to invite other users to play a Pong game through the
  chat interface.</li>
  <li>The tournament system should be able to warn users expected for the next
  game.</li>
  <li>The user should be able to access other players profiles through the chat interface.</li>
  </blockquote>
  </p>
  </details> 
  가성비 별로인 듯 해서 일단 보류

### DEVOPS

- Minor module: Monitoring system.

  <details><summary>details</summary>
  <p>
  <blockquote>
  In this minor module, the objective is to set up a comprehensive monitoring system
  using Prometheus and Grafana.<br>
  Key features and goals include:<br>
  <ul>
  <li>Deploy Prometheus as the monitoring and alerting toolkit to collect metrics
  and monitor the health and performance of various system components.</li>
  <li>Configure data exporters and integrations to capture metrics from different
  services, databases, and infrastructure components.</li>
  <li>Create custom dashboards and visualizations using Grafana to provide realtime insights into system metrics and performance.</li>
  <li>Set up alerting rules in Prometheus to proactively detect and respond to
  critical issues and anomalies.</li>
  <li>Ensure proper data retention and storage strategies for historical metrics data.</li>
  <li>Implement secure authentication and access control mechanisms for Grafana
  to protect sensitive monitoring data.</li>
  </ul>
  This minor module aims to establish a robust monitoring infrastructure using
  Prometheus and Grafana, enabling real-time visibility into system metrics and
  proactive issue detection for improved system performance and reliability.
  </blockquote>
  </p>
  </details> 
  hyunghki: 시간 남으면 구현 할게요.

### GRAPHICS

- Major module: Use of advanced 3D techniques.

  <details><summary>details</summary>
  <p>
  <blockquote>
  This major module, known as "Graphics," is focused on enhancing the visual aspects
  of the Pong game.<br>
  It introduces the utilization of advanced 3D techniques to create
  a more immersive gaming experience.<br>
  Specifically, the Pong game will be developed
  using ThreeJS/WebGL to achieve the desired visual effects.
  <ul>
  <li>Advanced 3D Graphics: The primary goal of this module is to implement
  advanced 3D graphics techniques to elevate the visual quality of the Pong
  game.<br>By utilizing ThreeJS/WebGL , we aim to create stunning visual effects
  that immerse players in the gaming environment.</li>
  <li>Immersive Gameplay: The incorporation of advanced 3D techniques enhances
  the overall gameplay experience by providing users with a visually engaging
  and captivating Pong game.</li>
  <li>Technology Integration: The chosen technology for this module is ThreeJS/WebGL.<br>
  These tools will be used to create the 3D graphics, ensuring compatibility and
  optimal performance.</li>
  </ul>
  This major module aims to revolutionize the Pong game’s visual elements by introducing advanced 3D techniques.<br>
  Through the utilization of TreeJS/WebGL , we
  aspire to provide players with an immersive and visually stunning gaming experience
  </bockquote>
  </p>
  </details> 
  그래픽에 관심은 없지만 다른 모듈과 상당히 독립적

### ACCSSIBILITY

- Minor module: Multiple language supports.
  <details><summary>details</summary>
  <p>
  <blockquote>
  In this minor module, the objective is to ensure that your website supports multiple
  languages to cater to a diverse user base.<br>
  Key features and goals include:
  <ul>
  <li>Implement support for a minimum of three languages on the website to accommodate a broad audience.</li>
  <li>Provide a language switcher or selector that allows users to easily change the
  website’s language based on their preferences.</li>
  <li>Translate essential website content, such as navigation menus, headings, and
  key information, into the supported languages.</li>
  <li>Ensure that users can navigate and interact with the website seamlessly, regardless of the selected language.</li>
  <li>Consider using language packs or localization libraries to simplify the translation process and maintain consistency 
  across different languages.</li>
  <li>Allow users to set their preferred language as a default choice for subsequent
  visits to the website.</li>
  </ul>
  This minor module aims to enhance the accessibility and inclusivity of your website
  by offering content in multiple languages, making it more user-friendly for a diverse
  international audience.
  </blockquote>
  </p>
  </details> 
  가능하긴 한데 그렇게 하고 싶지는 않음

- Minor module: Add accessibility for Visually Impaired Users.

  <details><summary>details</summary>
  <p>
  <blockquote>
  In this minor module, the goal is to make your website more accessible for visually
  impaired users.<br>
  Key features include:
  <ul>
  <li>Support for screen readers and assistive technologies.</li>
  <li>Clear and descriptive alt text for images.</li>
  <li>High-contrast color scheme for readability.</li>
  <li>Keyboard navigation and focus management.</li>
  <li>Options for adjusting text size.</li>
  <li>Regular updates to meet accessibility standards.</li>
  </ul>
  This module aims to improve the website’s usability for individuals with visual
  impairments and ensure compliance with accessibility standards.
  </blockquote>
  </p>
  </details> 
  시각 장애인이 퐁 게임을 어떻게 하는가

- Minor module: Server-Side Rendering (SSR) Integration.
  
  <details><summary>details</summary>
  <p>
  <blockquote>
  In this minor module, the focus is on integrating Server-Side Rendering (SSR)
  to enhance the performance and user experience of your website.<br>
  Key objectives include:
  <ul>
  <li>Implement SSR to improve the website’s loading speed and overall performance.</li>
  <li>Ensure that content is pre-rendered on the server and delivered to users’
  browsers for faster initial page loads.</li>
  <li>Optimize SEO by providing search engines with pre-rendered HTML content.</li>
  <li>Maintain a consistent user experience while benefiting from the advantages of
  SSR.</li>
  </ul>
  This module aims to boost website performance and SEO by integrating Server-Side
  Rendering for faster page loads and improved user experience
  </blockquote>
  </p>
  </details> 
  방향도 모르겠고 비용이 커 보임

### SERVER_SIDE PONG

- Major module: Replacing Basic Pong with Server-Side Pong and Implementing an API.
 
  <details><summary>details</summary>
  <p>
  <blockquote>
  In this major module, the goal is to replace the basic Pong game with a serverside Pong game, accompanied by the implementation of an API.<br>
  Key features and objectives include:
  <ul>
  <li>Develop server-side logic for the Pong game to handle gameplay, ball movement, scoring, and player interactions.</li>
  <li>Create an API that exposes the necessary resources and endpoints to interact
  with the Pong game, allowing partial usage of the game via the Command-Line
  Interface (CLI) and web interface.</li>
  <li>Design and implement the API endpoints to support game initialization, player
  controls, and game state updates.</li>
  <li>Ensure that the server-side Pong game is responsive, providing an engaging
  and enjoyable gaming experience.</li>
  <li>Integrate the server-side Pong game with the web application, allowing users
  to play the game directly on the website.</li>
  </ul>  
  This major module aims to elevate the Pong game by migrating it to the server
  side, enabling interaction through both a web interface and CLI while offering an
  API for easy access to game resources and features.
  </blockquote>
  </p>
  </details> 
  다른 모듈 하려면 필요해 보이고 어려워 보이지도 않음

**Comment by hijkl2e** [comment]
### Web
#### Major module: Use a Framework as backend. (3)
#### Minor module: Use a front-end framework or toolkit. (3)
#### Minor module: Use a database for the backend. (3)
#### Major module: Store the score of a tournament in the Blockchain. (1)

### User Management
#### Major module: Standard user management, authentication, users across tournaments. (3)
#### Major module: Implementing a remote authentication. (3)

### Gameplay and user experience
#### Major module: Remote players (3)
#### Major module: Multiplayers (more than 2 in the same game). (1)
#### Major module: Add Another Game with User History and Matchmaking. (1)
#### Minor module: Game Customization Options. (3)
#### Major module: Live chat. (2)

### AI-Algo
#### Minor module: User and Game Stats Dashboards (2)

### Cybersecurity
#### Major module: Implement Two-Factor Authentication (2FA) and JWT. (2)

### Devops
#### Major module: Infrastructure Setup for Log Management. (3)
#### Major module: Designing the Backend as Microservices. (3)

### Accessibility
#### Minor module: Support on all devices. (2)
#### Minor module: Expanding Browser Compatibility. (3)
#### Minor module: Multiple language supports. (2)
#### Minor module: Add accessibility for Visually Impaired Users. (1)
#### Minor module: Server-Side Rendering (SSR) Integration. (2)

### Server-Side Pong
#### Major module: Replacing Basic Pong with Server-Side Pong and Implementing an API. (2)

**Comment by cryscham123** [comment]
[여기](https://github.com/organization-for-practice/PONG_PONG/discussions/28)로 이동 했습니다.
